**Problem 1** Row Echelon Form and Rank

In [1]:
import numpy as np

#Initializing matrix for test case a) in Problem 1.1
A1_square = np.array([[1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 3, 1], [0, 0, 3, 0]], dtype=np.float64)

#Initializing matrix for test case b) in Problem 1.1
A2_square = np.array([[0, 1, 1], [2, 6, 4], [1, 1, 4]], dtype=np.float64)

**1.1** Row echelon form for square matrices by Gaussian elimination

In [3]:
def GE_square(A, print_flag):
  R = A.copy()
  n = R.shape[0]
  pvt_list = []
  k = 0
  eps = np.finfo(np.float32).eps
  #################### YOUR CODE STARTS HERE ####################
  for r in range(n):
    while np.amax(np.abs(R[r:n, k])) <= eps:
      k += 1
      if k == n:
        if print_flag:
          print("Early stop: no more non-zero columns.")
        return R, pvt_list

    # Row with largest absolute zero
    i = np.argmax(np.abs(R[r:n, k])) + r

    # Swap current row r with row i
    R[[r, i], :] = R[[i, r], :]
    pvt_list.append(k)

    if print_flag:
      print(f"After row swap (Row {r} with Row {i}):\n", R)
      print("Current pivot list:", pvt_list)

    # Remove all rows below row r
    for j in range(r + 1, n):
      lamb = R[j, k] / R[r, k]
      R[j, :] = R[j, :] - lamb * R[r, :]

    if print_flag:
      print(f"After elimination below Row {r}:\n", R)
      print("Current pivot list:", pvt_list)

  ###############################################################
  return R, pvt_list

In [4]:
R, pvt_idx_list = GE_square(A1_square, True)
# print out the row echelon form
print("row echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 0):
 [[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current pivot list: [0]
After elimination below Row 0:
 [[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current pivot list: [0]
After row swap (Row 1 with Row 2):
 [[1. 0. 1. 0.]
 [0. 0. 3. 1.]
 [0. 0. 0. 0.]
 [0. 0. 3. 0.]]
Current pivot list: [0, 2]
After elimination below Row 1:
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]
Current pivot list: [0, 2]
After row swap (Row 2 with Row 3):
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Current pivot list: [0, 2, 3]
After elimination below Row 2:
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Current pivot list: [0, 2, 3]
Early stop: no more non-zero columns.
row echelon form of A1_square:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[0, 2, 3]


In [5]:
R, pvt_idx_list = GE_square(A2_square, True)
# print out the row echelon form
print("row echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 1):
 [[2. 6. 4.]
 [0. 1. 1.]
 [1. 1. 4.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 2.  6.  4.]
 [ 0.  1.  1.]
 [ 0. -2.  2.]]
Current pivot list: [0]
After row swap (Row 1 with Row 2):
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  1.  1.]]
Current pivot list: [0, 1]
After elimination below Row 1:
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1]
After row swap (Row 2 with Row 2):
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1, 2]
After elimination below Row 2:
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1, 2]
row echelon form of A2_square:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[0, 1, 2]


**1.2**  Row echelon form for rectangular matrices by Gaussian elimination

In [7]:
#Initializing matrix for test case a) in Problem 1.2
A1_rect = np.array([[1, 2, 2, -1], [4, 8, 9, 6], [0, 3, 2, 9]], dtype=np.float64)

#Initializing matrix for test case b) in Problem 1.2
A2_rect = np.array([[1, 2, 3, 1, 2], [0, 4, 6, 0, 1], [2, 4, 8, 0, 0], [0, 1, 2, 0, 9]], dtype=np.float64)

In [8]:
def GE_rectangular(A, print_flag):
  R = A.copy()
  n = R.shape[0] #number of rows in A
  m = R.shape[1] #number of columns in A
  pvt_list = []
  k = 0
  eps = np.finfo(np.float32).eps
  #################### YOUR CODE STARTS HERE ####################
  for r in range(n):
    while k < m and np.amax(np.abs(R[r:n, k])) <= eps:
      k += 1
    if k == m:
      if print_flag:
        print("Early stop: no more non-zero columns.")
      return R, pvt_list
    i = np.argmax(np.abs(R[r:n, k])) + r

    # Swap current row r with row i
    R[[r, i], :] = R[[i, r], :]
    pvt_list.append(k)

    if print_flag:
      print(f"After row swap (Row {r} with Row {i}):\n", R)
      print("Current pivot list:", pvt_list)

    # Eliminate all rows below row r
    for j in range(r + 1, n):
      if R[r, k] != 0:
        lamb = R[j, k] / R[r, k]
        R[j, :] = R[j, :] - lamb * R[r, :]

    if print_flag:
      print(f"After elimination below Row {r}:\n", R)
      print("Current pivot list:", pvt_list)

    # next iteration
    k += 1

  ###############################################################
  return R, pvt_list

In [9]:
R, pvt_idx_list = GE_rectangular(A1_rect, True)
# print out the row echelon form
print("row echelon form of A1_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 1):
 [[ 4.  8.  9.  6.]
 [ 1.  2.  2. -1.]
 [ 0.  3.  2.  9.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 4.    8.    9.    6.  ]
 [ 0.    0.   -0.25 -2.5 ]
 [ 0.    3.    2.    9.  ]]
Current pivot list: [0]
After row swap (Row 1 with Row 2):
 [[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Current pivot list: [0, 1]
After elimination below Row 1:
 [[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Current pivot list: [0, 1]
After row swap (Row 2 with Row 2):
 [[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Current pivot list: [0, 1, 2]
After elimination below Row 2:
 [[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Current pivot list: [0, 1, 2]
row echelon form of A1_rect:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[0, 1, 2]


In [10]:
R, pvt_idx_list = GE_rectangular(A2_rect, True)
# print out the row echelon form
print("row echelon form of A2_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 2):
 [[2. 4. 8. 0. 0.]
 [0. 4. 6. 0. 1.]
 [1. 2. 3. 1. 2.]
 [0. 1. 2. 0. 9.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 2.  4.  8.  0.  0.]
 [ 0.  4.  6.  0.  1.]
 [ 0.  0. -1.  1.  2.]
 [ 0.  1.  2.  0.  9.]]
Current pivot list: [0]
After row swap (Row 1 with Row 1):
 [[ 2.  4.  8.  0.  0.]
 [ 0.  4.  6.  0.  1.]
 [ 0.  0. -1.  1.  2.]
 [ 0.  1.  2.  0.  9.]]
Current pivot list: [0, 1]
After elimination below Row 1:
 [[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.5   0.    8.75]]
Current pivot list: [0, 1]
After row swap (Row 2 with Row 2):
 [[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.5   0.    8.75]]
Current pivot list: [0, 1, 2]
After elimination below Row 2:
 [[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.    0.5   9.75]]
Curren

In [11]:
#test your implementation on Eq. (3) (i.e., the worked square example) for debugging

R, pvt_idx_list = GE_rectangular(A1_square, True)
# print out the row echelon form
print("row echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 0):
 [[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current pivot list: [0]
After elimination below Row 0:
 [[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current pivot list: [0]
After row swap (Row 1 with Row 2):
 [[1. 0. 1. 0.]
 [0. 0. 3. 1.]
 [0. 0. 0. 0.]
 [0. 0. 3. 0.]]
Current pivot list: [0, 2]
After elimination below Row 1:
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]
Current pivot list: [0, 2]
After row swap (Row 2 with Row 3):
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Current pivot list: [0, 2, 3]
After elimination below Row 2:
 [[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Current pivot list: [0, 2, 3]
Early stop: no more non-zero columns.
row echelon form of A1_square:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[0, 2, 3]


In [12]:
#test your implementation on Eq. (4) (i.e., the worked square example) for debugging

R, pvt_idx_list = GE_rectangular(A2_square, True)
# print out the row echelon form
print("row echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

After row swap (Row 0 with Row 1):
 [[2. 6. 4.]
 [0. 1. 1.]
 [1. 1. 4.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 2.  6.  4.]
 [ 0.  1.  1.]
 [ 0. -2.  2.]]
Current pivot list: [0]
After row swap (Row 1 with Row 2):
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  1.  1.]]
Current pivot list: [0, 1]
After elimination below Row 1:
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1]
After row swap (Row 2 with Row 2):
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1, 2]
After elimination below Row 2:
 [[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list: [0, 1, 2]
row echelon form of A2_square:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[0, 1, 2]


**1.3** Matrix rank and number of pivots

In [14]:
X = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 4]], dtype=np.float64)
Y = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
Z = np.array([[1, 2, 4, 1], [3, 5, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
# please use GE_rectangular to generate the reduced row echelon form of matrices X, Y, Z
# And then check the rank of each matrix visually
############################# YOUR CODE STARTS HERE #############################

R_X, pvt_idx_X = GE_rectangular(X, True)
R_Y, pvt_idx_Y = GE_rectangular(Y, True)
R_Z, pvt_idx_Z = GE_rectangular(Z, True)

# Checking Rank
rank_X = len(pvt_idx_X)
rank_Y = len(pvt_idx_Y)
rank_Z = len(pvt_idx_Z)

# Output
print("Reduced Row Echelon Form of X:")
print(R_X)
print("Rank of X:", rank_X)

print("\nReduced Row Echelon Form of Y:")
print(R_Y)
print("Rank of Y:", rank_Y)

print("\nReduced Row Echelon Form of Z:")
print(R_Z)
print("Rank of Z:", rank_Z)

################################################################################


After row swap (Row 0 with Row 2):
 [[ 4.  8. 16.  4.]
 [ 3.  6. 12.  3.]
 [ 1.  2.  4.  1.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 4.  8. 16.  4.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Current pivot list: [0]
Early stop: no more non-zero columns.
After row swap (Row 0 with Row 2):
 [[ 4.  8. 16.  6.]
 [ 3.  6. 12.  3.]
 [ 1.  2.  4.  1.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.  -0.5]]
Current pivot list: [0]
After row swap (Row 1 with Row 1):
 [[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.  -0.5]]
Current pivot list: [0, 3]
After elimination below Row 1:
 [[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.   0. ]]
Current pivot list: [0, 3]
Early stop: no more non-zero columns.
After row swap (Row 0 with Row 2):
 [[ 4.  8. 16.  6.]
 [ 3.  5. 12.  3.]
 [ 1.  2.  4.  1.]]
Current pivot list: [0]
After elimination below Row 0:
 [[ 4.   8.  16.   6. ]
 [ 0.  -1.   

In [16]:
from numpy.linalg import matrix_rank
#########Validate the answers about the matrices rank###########################
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)
################################################################################

**Please double-click here and fill in the rank and dimension of nullspace of the these matrices**

rank(X) = 1, dimension of null(X) = 3

rank(Y) = 2, dimension of null(Y) = 2

rank(Z) = 3, dimension of null(Z) = 1
